config/routes.rb
CsmStudents::Application.routes.draw do
  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/special_controller.rb
class SpecialController < ApplicationController
	def hello
	 @name = params[:name]	
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
    @students = Student.all
	end
  def edit
    @student = Student.find(params[:id])
  end
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(params[:student])
      redirect_to students_path
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CsmStudents</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/special/hello.html.erb
Hi <%= @name %>!

app/views/students/edit.html.erb
<h1> Editing Student #<%= @student.id %></h1>
<%= semantic_form_for(@student) do |f| %>
<%= f.inputs do %>
    <%= f.input :first_name %>
		<%= f.input :last_name %>
<% end %>
<%= f.actions do %>
<%= f.action :submit, :as => :button %>
<% end %>
	
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td> 
        <%= link_to "edit", edit_student_path(student) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>